### ISSUE TITLE
__inline('xxx.tpl') Warning

### ISSUE THREAD

**Issue by hanai** [fex-team/fis3-plugin-module#4]
原js文件

``` js
// @require /static/require.js

define(function (require, exports, module) {
    var cal = require('../cal/cal');
    console.log('work');
    // 1 - 0
    console.log(cal.min(1, 0));
    var test = __inline('test.tpl');
});
```

test.tpl

``` html
<p>Hello world!</p>
```

错误

```
[WARNI] Got Error: Line 8: Unexpected token ILLEGAL while parse [/comp/1-0/1-0.js].
```

生成的文件

``` js
// @require static/require.js

define(function (require, exports, module) {
    var cal = require('../cal/cal');
    console.log('work');
    // 1 - 0
    console.log(cal.min(1, 0));
    var test = "<p>Hello world!</p>\n";
});
```

**Comment by hanai** [comment]
在加上verbose

```
 [DEBUG] 11:29:40.918 builtin standard for [/Users/hanai/WebstormProjects/fis3-demo/use-amd/comp/1-0/1-0.js] start

 [WARNI] Got Error: Line 8: Unexpected token ILLEGAL while parse [/comp/1-0/1-0.js].

 [DEBUG] 11:29:40.927 Error: Line 8: Unexpected token ILLEGAL
    at createError (/usr/local/lib/node_modules/fis3-hook-module/node_modules/esprima/esprima.js:2336:21)
    at unexpectedTokenError (/usr/local/lib/node_modules/fis3-hook-module/node_modules/esprima/esprima.js:2412:13)
    at throwUnexpectedToken (/usr/local/lib/node_modules/fis3-hook-module/node_modules/esprima/esprima.js:2416:15)
    at scanPunctuator (/usr/local/lib/node_modules/fis3-hook-module/node_modules/esprima/esprima.js:807:13)
    at advance (/usr/local/lib/node_modules/fis3-hook-module/node_modules/esprima/esprima.js:1592:16)
    at collectToken (/usr/local/lib/node_modules/fis3-hook-module/node_modules/esprima/esprima.js:1605:17)
    at lex (/usr/local/lib/node_modules/fis3-hook-module/node_modules/esprima/esprima.js:1647:61)
    at expect (/usr/local/lib/node_modules/fis3-hook-module/node_modules/esprima/esprima.js:2432:21)
    at parseArguments (/usr/local/lib/node_modules/fis3-hook-module/node_modules/esprima/esprima.js:3212:9)
    at parseLeftHandSideExpressionAllowCall (/usr/local/lib/node_modules/fis3-hook-module/node_modules/esprima/esprima.js:3304:24)
```

**Comment by 2betop** [comment]
表示现在无法复现此Bug，求 fis-conf.js 配置

**Comment by hanai** [comment]
fis-conf.js

``` js
// npm install [-g] fis3-hook-module
fis.hook('module', {
    mode: 'amd'
});

fis.match('/comp/**/*.js', {
    isMod: true, // 设置 comp 下都是一些组件，组件建议都是匿名方式 define
    release: '/static/$0'
});

fis.match('::package', {
    // npm install [-g] fis3-postpackager-loader
    // 分析 __RESOURCE_MAP__ 结构，来解决资源加载问题
    postpackager: fis.plugin('loader', {
        resourceType: 'amd',
        useInlineMap: true // 资源映射表内嵌
    })
});
```

```
fis3@3.0.1
fis3-hook-module@1.0.7
fis3-postpackager-loader@1.0.19
```

**Comment by 2betop** [comment]
更新  `fis3-hook-module@1.0.8`，fis 中间码导致 语法分析出错，现已修复此问题。
